# Generated by Django 5.1.2 on 2024-10-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="querylog",
            name="indexes_used",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="querylog",
            name="records_processed",
            field=models.IntegerField(default=0),
        ),
    ]
