# Generated by Django 5.1.2 on 2024-10-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database_manager", "0002_querylog_indexes_used_querylog_records_processed"),
    ]

    operations = [
        migrations.AddField(
            model_name="querylog",
            name="columns_accessed",
            field=models.TextField(blank=True, null=True),
        ),
    ]
